name: Addition scopes build (MT)

on:
  push:
    branches: [ "addition-scopes" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: src/engine-vs2022.sln
  PACK_GAMEDATA_NAME: 00_modded_exes_gamedata.db0

jobs:
  pack_gamedata:
    name: pack_gamedata
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Pack gamedata
      run: |
        new-item -path "./compressor/gamedata" -itemtype directory -force
        copy-item -path "./gamedata/*" -destination "./compressor/gamedata" -recurse -force
        cd ./compressor
        start-process -filepath "./! compress_gamedata.cmd" -Wait
        rename-item -path gamedata.db0 -newname ${{env.PACK_GAMEDATA_NAME}}

    - name: Upload gamedata
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ${{env.PACK_GAMEDATA_NAME}}
        path: ./compressor/${{env.PACK_GAMEDATA_NAME}}
        if-no-files-found: "error"
        retention-days: 7

  build:
    name: build-${{matrix.buildconf}}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        buildconf: ["DX11", "DX11-AVX"]
    steps:
    - name: Configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.3
      with:
        minimum-size: 8GB
        maximum-size: 8GB
        disk-root: "C:"

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Init submodules
      uses: snickerbockers/submodules-init@v4

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: "x64"

    - name: Build ${{matrix.buildconf}}
      run: msbuild /p:Configuration=${{matrix.buildconf}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Exe
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ${{matrix.buildconf}}_mt_exe
        path: ./_build/_game/bin_dbg/*.exe
        if-no-files-found: "error"
        retention-days: 7
